<?php
/**
 * @file learn_glue.module
 */

/**
 * Implements hook_block_info().
 */
function learn_glue_block_info() {
  $blocks = array();
  $blocks['learn_glue_contribute'] = array(
    'info' => t('Contribute'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function learn_glue_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'learn_glue_contribute':
      $links = array();
      $links[] = array(
        'href' => 'http://drupal.org/project/issues/learn',
        'title' => t('Learn install profile issue queue'),
      );
      $links[] = array(
        'href' => 'http://drupal.org/project/issues/ladder',
        'title' => t('Ladder module issue queue'),
      );
      $links[] = array(
        'href' => 'http://drupal.org/project/issues/lessons',
        'title' => t('Lessons module issue queue'),
      );

      $block['subject'] = t('Contribute');
      $block['content'] = array(
        '#theme' => 'links',
        '#links' => $links,
      );
      break;
  }

  return $block;
}
